apiVersion: apps/v1
kind: Deployment
metadata:
  name: application1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application1      
  template:
    metadata:
      labels:
        app: application1
    spec:      
      containers:
      - name: application1
        image: rojha63/my-app:11.0.0
        ports:
        - containerPort: 80		  
---
kind: Service
apiVersion: v1
metadata:
  name: application1-svc-np
spec:
  type: NodePort
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 80
  selector:
     app: application1  
---
kind: Service
apiVersion: v1
metadata:
  name: application1-svc-ldb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 32000
  selector:
     app: application1  
